---
pin: false
schedule: "every day"
update: "insecure"
requirements:
  - requirements.in:
      update: "insecure"
      pin: false
  - requirements_dev.in:
      update: "insecure"
      pin: false
...
